# Database Parameters
database:
  key_size: 16
  value_size: 100
  nr_entry: 1048576

# Workload Parameters
workload:
  nr_warmup_op: 100
  nr_op: 1000
  nr_thread: 4
  next_op_interval_ns: 0  # use 50000 on mars
  operation_proportion:
    read: 0.1
    update: 0.05
    insert: 0.35
    scan: 0.05
    read_modify_write: 0.45
  request_distribution: "uniform"
  # for zipfian distribution
  zipfian_constant: 0.99
  # for trace workload
  trace_file_list:
    - "./cur_trace"
  # for scan operation
  scan_length: 100

# LevelDB Parameters
leveldb:
  data_dir: "/mydata/leveldb_db"
  cache_size: 100000000
  print_stats: true
