# Database Parameters
database:
  key_size: 16
  value_size: 100
  nr_entry: 1073741824

# Workload Parameters
workload:
  nr_warmup_op: 0
  nr_op: 3000000
  nr_thread: 1
  next_op_interval_ns: 0  # use 50000 on mars
  operation_proportion:
    read: 0
    update: 0
    insert: 0.05
    scan: 0.95
    read_modify_write: 0
  request_distribution: "zipfian"
  # for zipfian distribution
  zipfian_constant: 0.99
  # for trace workload
  trace_file_list:
    - "./cur_trace"
  # for scan operation
  scan_length: 100

# LevelDB Parameters
leveldb:
  data_dir: "/mydata/leveldb_db"
  cache_size: 100000000
  print_stats: true
